### PR TITLE
Make fields in BuildImageXXXDetail public

### LINKED ISSUE #14: Make fields in `BuildImageXXXDetail` public
This is the current definition of `BuildImageXXXDetail` structs.

```rust
/// Subtype for the [Build Image Results](struct.BuildImageResults.html) type.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildImageAuxDetail {
    #[serde(rename = "ID")]
    id: String,
}

/// Subtype for the [Build Image Results](struct.BuildImageResults.html) type.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildImageErrorDetail {
    code: Option<u64>,
    message: String,
}

/// Subtype for the [Build Image Results](struct.BuildImageResults.html) type.
#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildImageProgressDetail {
    current: Option<u64>,
    total: Option<u64>,
}
```

I was trying to show error messages to users for a build failure. However, the current definition prevents the code below because the fields are private.

```rust
match build_image_result {
    ...
    BuildImageError { error, error_detail } => {
        // this fails because the message field is private
        eprintln!("{}", &error_detail.message);
    }
    ...
}
```

### PR DESCRIPTION
**Pull request by Qwaz**
Fixes #14

### CODE REVIEW

File: src/image.rs [hunk 1]
```diff
@@ -855,23 +855,23 @@ impl<'a> BuildImageQueryParams<&'a str> for BuildImageOptions<String> {
 #[serde(deny_unknown_fields)]
```
Comment (fussybeaver) [inline src/image.rs]: You'll need to add `#[allow(missing_docs)]` to all the structs that now have public methods to get it to compile.

Comment (Qwaz) [reply src/image.rs]: Thanks for the comment. I pushed a new commit to fix this.
